# config/packages/security.yaml
security:
    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        ROLE_STUDENT:     IS_AWAITING_VALIDATION
        ROLE_ADMIN:       ROLE_STUDENT
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/confirm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_STUDENT }
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login
                default_target_path: admin_dashboard
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 15