logout:
    path: /logout

homepage:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin/dashboard
        permanent: true